/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.DataBaseConn;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jorge
 */
public class VistaFacturas extends javax.swing.JFrame {

    /**
     * Creates new form Facturas
     */
    public VistaFacturas() {
        initComponents();
         // TODO add your handling code here:
        Object[][] filasDatos  = new Object[1][5];
        Object[] nombreColumnas = {"Fecha","Factura No","Cliente","Total"};
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(nombreColumnas);
        jTable1.setModel(modelo);
        DataBaseConn db = new DataBaseConn();
       
        try {
            List<modelo.Facturas> lista;
            lista = db.mostrarFacturas();
        
        
        for(modelo.Facturas f : lista){
            
            filasDatos[0][0] = f.getIdFactura();
            filasDatos[0][1] = f.getFecha();
            filasDatos[0][2] = f.getNumeroFactura();
            filasDatos[0][3] = f.getNombreCliente();
            filasDatos[0][4] = f.getTotal();
            modelo.addRow(filasDatos[0]);
        
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaFacturas.class.getName()).log(Level.SEVERE, null, ex);
       
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Ver Factura Seleccionada");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Crear Factura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar Facturas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar Factura");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(123, 123, 123))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton2)
                        .addGap(44, 44, 44)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int column = 0;
        int row = jTable1.getSelectedRow();
        if(jTable1.getSelectionModel().isSelectionEmpty()){
        showMessageDialog(null, "Seleccione una factura de la lista");
        }else{
            String value = jTable1.getModel().getValueAt(row, column).toString();
            int idFactura=Integer.parseInt(value);
            VerFactura vf = new VerFactura(idFactura);
        vf.setVisible(true); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CrearFactura cf = new CrearFactura();
        cf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Object[][] filasDatos  = new Object[1][5];
        Object[] nombreColumnas = {"id", "Fecha","Factura No","Cliente","Total"};
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(nombreColumnas);
        jTable1.setModel(modelo);
        DataBaseConn db = new DataBaseConn();
       
        try {
            List<modelo.Facturas> lista;
            lista = db.mostrarFacturas();
        
        
        for(modelo.Facturas f : lista){
            
            filasDatos[0][0] = f.getIdFactura();
            filasDatos[0][1] = f.getFecha();
            filasDatos[0][2] = f.getNumeroFactura();
            filasDatos[0][3] = f.getNombreCliente();
            filasDatos[0][4] = f.getTotal();
            modelo.addRow(filasDatos[0]);
        
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaFacturas.class.getName()).log(Level.SEVERE, null, ex);
       
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int column = 0;
        int row = jTable1.getSelectedRow();
        if(jTable1.getSelectionModel().isSelectionEmpty()){
        showMessageDialog(null, "Seleccione una factura de la lista");
        }else{
            String value = jTable1.getModel().getValueAt(row, column).toString();
            int idFactura=Integer.parseInt(value);
            DataBaseConn db = new DataBaseConn();
            try {
                db.borrarFactura(idFactura);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VistaFacturas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        Object[][] filasDatos  = new Object[1][5];
        Object[] nombreColumnas = {"id", "Fecha","Factura No","Cliente","Total"};
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(nombreColumnas);
        jTable1.setModel(modelo);
        DataBaseConn db = new DataBaseConn();
       
        try {
            List<modelo.Facturas> lista;
            lista = db.mostrarFacturas();
        
        
        for(modelo.Facturas f : lista){
            
            filasDatos[0][0] = f.getIdFactura();
            filasDatos[0][1] = f.getFecha();
            filasDatos[0][2] = f.getNumeroFactura();
            filasDatos[0][3] = f.getNombreCliente();
            filasDatos[0][4] = f.getTotal();
            modelo.addRow(filasDatos[0]);
        
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaFacturas.class.getName()).log(Level.SEVERE, null, ex);
       
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
